
MYSQL_CONCPP_DIR = "C:/Program Files/MySQL/Connector C++ 8.0"
CPPFLAGS = -I $(MYSQL_CONCPP_DIR)/include -L $(MYSQL_CONCPP_DIR)/lib64
LDLIBS = -lmysql
CXXFLAGS = -std=c++11
mysql_connection : mysql_connection.cpp